application:
  name: go-monorepo-boilerplate
  version: 1.0.0
  mode: dev #dev|prod
  maintenance: false #true|false
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net

services:
  auth-service:
    host: localhost
    port: 8080
  user-service:
    host: localhost
    port: 8081

db:
  username: root
  password:
  host: localhost
  port: 3306
  database: test_ent
  maxIdleConn: 10
  maxOpenConn: 100

outbound:
  quotes:
    get-url: https://programming-quotesapi.vercel.app/api/random
    post-url: https://en8trqq30hty3.x.pipedream.net/

smtp:
  username:
  password:
  ttl:
  type:

cache:
  configs:
    redis:
      host: localhost
      port: 6379
      username:
      password:
      db: 0
      poolSize: 10
  ttl:
    short-period: 3h
    medium-period: 24h
    long-period: 3d
